# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(691, 422)
        MainWindow.setFixedSize(691,422)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-1, -1, 141, 421))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.borrow = QtWidgets.QPushButton(self.frame)
        self.borrow.setGeometry(QtCore.QRect(0, 140, 141, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.borrow.setFont(font)
        self.borrow.setStyleSheet("color: white;\n"
"background-color: #23395d;")
        self.borrow.setObjectName("borrow")
        self.home = QtWidgets.QPushButton(self.frame)
        self.home.setGeometry(QtCore.QRect(0, 60, 141, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.home.setFont(font)
        self.home.setStyleSheet("color: white;\n"
"background-color: #23395d;")
        self.home.setObjectName("home")
        self.signout = QtWidgets.QPushButton(self.frame)
        self.signout.setGeometry(QtCore.QRect(0, 300, 141, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.signout.setFont(font)
        self.signout.setStyleSheet("color: white;\n"
"background-color: #23395d;")
        self.signout.setObjectName("signout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.rent = QtWidgets.QPushButton(self.frame)
        self.rent.setGeometry(QtCore.QRect(0, 220, 141, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rent.setFont(font)
        self.rent.setStyleSheet("color: white;\n"
"background-color: #23395d;\n"
"")
        self.rent.setObjectName("rent")
        self.displayFrame = QtWidgets.QFrame(self.centralwidget)
        self.displayFrame.setGeometry(QtCore.QRect(139, 0, 551, 371))
        self.displayFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.displayFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.displayFrame.setObjectName("displayFrame")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 691, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.borrow.setText(_translate("MainWindow", "Borrow Books"))
        self.home.setText(_translate("MainWindow", "Home"))
        self.signout.setText(_translate("MainWindow", "Sign Out"))
        self.label.setText(_translate("MainWindow", "DashBoard"))
        self.rent.setText(_translate("MainWindow", "Rentals"))


