# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Home.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_homeFrame(object):
    def setupUi(self, homeFrame):
        homeFrame.setObjectName("homeFrame")
        homeFrame.setWindowModality(QtCore.Qt.NonModal)
        homeFrame.resize(551, 371)
        homeFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        homeFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label = QtWidgets.QLabel(homeFrame)
        self.label.setGeometry(QtCore.QRect(200, 20, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.overdueBooksTable = QtWidgets.QTableWidget(homeFrame)
        self.overdueBooksTable.setGeometry(QtCore.QRect(35, 60, 481, 251))
        self.overdueBooksTable.setObjectName("overdueBooksTable")
        self.overdueBooksTable.setColumnCount(0)
        self.overdueBooksTable.setRowCount(0)

        self.retranslateUi(homeFrame)
        QtCore.QMetaObject.connectSlotsByName(homeFrame)

    def retranslateUi(self, homeFrame):
        _translate = QtCore.QCoreApplication.translate
        homeFrame.setWindowTitle(_translate("homeFrame", "Frame"))
        self.label.setText(_translate("homeFrame", "Books Overdue"))


