# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(333, 192)
        MainWindow.setFixedSize(333,192)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.userButton = QtWidgets.QPushButton(self.centralwidget)
        self.userButton.setGeometry(QtCore.QRect(50, 60, 101, 51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Img/user_button_icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.userButton.setIcon(icon)
        self.userButton.setIconSize(QtCore.QSize(90, 23))
        self.userButton.setObjectName("userButton")
        self.adminButton = QtWidgets.QPushButton(self.centralwidget)
        self.adminButton.setGeometry(QtCore.QRect(180, 60, 101, 51))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Img/admin_button_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.adminButton.setIcon(icon1)
        self.adminButton.setIconSize(QtCore.QSize(90, 23))
        self.adminButton.setFlat(False)
        self.adminButton.setObjectName("adminButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 333, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.userButton.setText(_translate("MainWindow", "User"))
        self.adminButton.setText(_translate("MainWindow", "Administrator"))



