# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Rent.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(551, 371)
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(230, 10, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.rentButton = QtWidgets.QPushButton(Frame)
        self.rentButton.setGeometry(QtCore.QRect(430, 328, 91, 23))
        self.rentButton.setObjectName("rentButton")
        self.bookTable = QtWidgets.QTableWidget(Frame)
        self.bookTable.setGeometry(QtCore.QRect(35, 50, 481, 271))
        self.bookTable.setObjectName("bookTable")
        self.bookTable.setColumnCount(0)
        self.bookTable.setRowCount(0)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "Rent Book"))
        self.rentButton.setText(_translate("Frame", "RENT"))


