# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Return.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(551, 372)
        self.returnButton = QtWidgets.QPushButton(Frame)
        self.returnButton.setGeometry(QtCore.QRect(420, 320, 75, 23))
        self.returnButton.setObjectName("returnButton")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(200, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.rentedBookTable = QtWidgets.QTableWidget(Frame)
        self.rentedBookTable.setGeometry(QtCore.QRect(25, 50, 501, 261))
        self.rentedBookTable.setObjectName("rentedBookTable")
        self.rentedBookTable.setColumnCount(0)
        self.rentedBookTable.setRowCount(0)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.returnButton.setText(_translate("Frame", "Return Book"))
        self.label.setText(_translate("Frame", "Rented Books"))


