# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignIn.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignIn(object):
    def setupUi(self, SignIn):
        SignIn.setObjectName("SignIn")
        SignIn.resize(388, 212)
        SignIn.setFixedSize(388,212)
        self.centralwidget = QtWidgets.QWidget(SignIn)
        self.centralwidget.setObjectName("centralwidget")
        self.usernameField = QtWidgets.QLineEdit(self.centralwidget)
        self.usernameField.setGeometry(QtCore.QRect(130, 30, 171, 20))
        self.usernameField.setObjectName("usernameField")
        self.passwordField = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordField.setGeometry(QtCore.QRect(130, 60, 171, 20))
        self.passwordField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordField.setPlaceholderText("")
        self.passwordField.setObjectName("passwordField")
        self.createButton = QtWidgets.QPushButton(self.centralwidget)
        self.createButton.setGeometry(QtCore.QRect(20, 150, 131, 23))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Img/new_user_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createButton.setIcon(icon)
        self.createButton.setIconSize(QtCore.QSize(21, 36))
        self.createButton.setFlat(True)
        self.createButton.setObjectName("createButton")
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(100, 100, 181, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Img/signin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loginButton.setIcon(icon1)
        self.loginButton.setIconSize(QtCore.QSize(23, 30))
        self.loginButton.setObjectName("loginButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 30, 47, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 47, 21))
        self.label_2.setObjectName("label_2")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(300, 150, 75, 23))
        self.backButton.setFlat(True)
        self.backButton.setObjectName("backButton")
        SignIn.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SignIn)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 388, 21))
        self.menubar.setObjectName("menubar")
        SignIn.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SignIn)
        self.statusbar.setObjectName("statusbar")
        SignIn.setStatusBar(self.statusbar)

        self.retranslateUi(SignIn)
        QtCore.QMetaObject.connectSlotsByName(SignIn)

    def retranslateUi(self, SignIn):
        _translate = QtCore.QCoreApplication.translate
        SignIn.setWindowTitle(_translate("SignIn", "MainWindow"))
        self.createButton.setText(_translate("SignIn", "Create Account?"))
        self.loginButton.setText(_translate("SignIn", "LOGIN"))
        self.label.setText(_translate("SignIn", "Username:"))
        self.label_2.setText(_translate("SignIn", "Password"))
        self.backButton.setText(_translate("SignIn", "Back"))


